# Generated by Django 4.0.2 on 2022-02-25 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photojournal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photojournal.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='message',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=True, upload_to='static/imgs/posts'),
        ),
    ]
