# Generated by Django 4.0.3 on 2022-03-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photojournal', '0006_alter_post_likes_alter_post_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
